weights: weights/yolov5s.pt
cfg: models/y5s_model_kim.yaml
data: data/knu_tour_yun.yaml
hyp:
  lr0: 0.002
  lrf: 0.002
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.07
  box: 0.05
  cls: 0.7
  cls_pw: 0.8
  obj: 1.3
  obj_pw: 1.2
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 1.0
  hsv_h: 0.015
  hsv_s: 0.5
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.1
  copy_paste: 0.0
epochs: 300
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '1'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: v5s_knu_class6
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/v5s_knu_class6
